steps:
  # Build l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}'
      - '-f'
      - 'cloud_job_epbs/Dockerfile'
      - '.'

images:
  - '${_IMAGE_NAME}'

substitutions:
  _IMAGE_NAME: 'gcr.io/ecoledesponts/spyfu-epbs-collection'

timeout: '1200s'
